services:
  backend:
    volumes:
      - ./:/app:cached
      - ./logs:/app/logs
    command: sh -c "pip install -r requirements.txt --no-cache-dir || true && uvicorn server.api:app --app-dir /app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/server"
    environment:
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8000:8000"

  ui:
    volumes:
      - ./:/app:cached
      - ./logs:/app/logs
    command: sh -c "pip install -r requirements.txt --no-cache-dir || true && streamlit run ui/ui_dashboard.py --server.port 8501 --server.address 0.0.0.0"
    ports:
      - "8501:8501"

  bot:
    volumes:
      - ./:/app:cached
      - ./logs:/app/logs
    command: sh -c "pip install -r requirements.txt --no-cache-dir || true && python -m server.bot"
